// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1750282577);
user_pref("app.update.lastUpdateTime.background-update-timer", 1750282577);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1750282577);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1750282577);
user_pref("basebrowser.migration.version", 3);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 148);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.security_level.noscript_inited", true);
user_pref("browser.security_level.security_custom", false);
user_pref("browser.security_level.security_slider", 4);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage", "chrome://browser/content/blanktab.html");
user_pref("browser.startup.homepage_override.buildID", "20250526202532");
user_pref("browser.startup.homepage_override.mstone", "128.11.0");
user_pref("browser.startup.homepage_override.mullvadbrowser.version", "14.5.3");
user_pref("browser.startup.lastColdStartupCheck", 1750370657);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"new-identity-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"_d19a89b9-76c1-4a61-bcd4-49e8de916403_-browser-action\",\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"_d19a89b9-76c1-4a61-bcd4-49e8de916403_-browser-action\",\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"unified-extensions-area\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":20,\"currentVersionBaseBrowser\":2,\"currentVersionMullvadBrowser\":1,\"newElementCount\":0}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("browser.urlbar.recentsearches.lastDefaultChanged", "1750282572490");
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("distribution.iniFile.exists.appversion", "128.11.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.nixos.bookmarksProcessed", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("dom.security.https_only_mode_ever_enabled_pbm", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.installedDistroAddon.uBlock0@raymondhill.net", true);
user_pref("extensions.installedDistroAddon.{73a6fe31-595d-460b-a920-fcc0f8843232}", true);
user_pref("extensions.installedDistroAddon.{d19a89b9-76c1-4a61-bcd4-49e8de916403}", true);
user_pref("extensions.lastAppBuildId", "20250526202532");
user_pref("extensions.lastAppVersion", "128.11.0");
user_pref("extensions.lastMullvadBrowserVersion", "14.5.3");
user_pref("extensions.lastPlatformVersion", "128.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{73a6fe31-595d-460b-a920-fcc0f8843232}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{d19a89b9-76c1-4a61-bcd4-49e8de916403}", true);
user_pref("extensions.webextensions.uuids", "{\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":\"837153ea-f589-4df2-801b-77e10db47027\",\"uBlock0@raymondhill.net\":\"ad54c6e5-50b3-420f-8d1a-cd06d789138e\",\"{d19a89b9-76c1-4a61-bcd4-49e8de916403}\":\"898a7549-4360-4505-afa0-c2ecbd9a6103\",\"default-theme@mozilla.org\":\"ba4f1fed-0186-4336-b436-329524d3b75a\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("intl.accept_languages", "en-US, en");
user_pref("intl.language_notification.shown", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("mullvadbrowser.migration.version", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.resistFingerprinting.letterboxing.didForceSize", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4f1a1f19-4761-4d91-9851-7dd01371fd74");
user_pref("toolkit.startup.last_success", 1750370656);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
